import { IDataBids } from './table-bids';
import { IDataCandidates } from './table-candidates';
import { IDataVacancy } from './table-vacancy';

// заявки
export let dataBids: IDataBids[] = [
  {
    date: '12.11.2022',
    vacancy: 'Вакансия 1',
    status: 'Черновик',
  },
  {
    date: '01.07.1989',
    vacancy: 'Вакансия 2',
    status: 'Закрыта',
  },
  {
    date: '11.01.2015',
    vacancy: 'Вакансия 3',
    status: 'Отклонена',
  },
  {
    date: '12.11.2021',
    vacancy: 'Вакансия 1',
    status: 'Отклонена',
  },
  {
    date: '03.07.1989',
    vacancy: 'Вакансия 4',
    status: 'Отклонена',
  },
  {
    date: '11.01.2016',
    vacancy: 'Вакансия 5',
    status: 'Закрыта',
  },
  {
    date: '12.11.2017',
    vacancy: 'Вакансия 6',
    status: 'Закрыта',
  },
  {
    date: '02.07.1989',
    vacancy: 'Вакансия 7',
    status: 'Черновик',
  },
  {
    date: '11.01.2018',
    vacancy: 'Вакансия 8',
    status: 'Черновик',
  },
  {
    date: '11.01.2010',
    vacancy: 'Вакансия 5',
    status: 'Закрыта',
  },
  {
    date: '12.11.2009',
    vacancy: 'Вакансия 6',
    status: 'Закрыта',
  },
  {
    date: '12.07.2009',
    vacancy: 'Вакансия 6',
    status: 'Закрыта',
  },
  {
    date: '01.07.1989',
    vacancy: 'Вакансия 7',
    status: 'Черновик',
  },
  {
    date: '11.01.2015',
    vacancy: 'Вакансия 8',
    status: 'Черновик',
  },
];

// кандидаты
export let dataCandidates: IDataCandidates[] = [
  {
    vacancy: {
      name: 'Дизайнер',
      candidates: ['Петров Петр Петрович', 'Смирнов Сергей Александрович'],
    },
    fullname: 'Иванов Иван Иванович',
    event: 'Резюме у заказчика',
    resume: 'resume 1',
  },
  {
    vacancy: {
      name: 'Рекрутер',
      candidates: [
        'Васильев Василий Васильевич',
        'Кузнецов Константин Константинович',
      ],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Проверка СБ',
    resume: 'resume 2',
  },
  {
    vacancy: {
      name: 'Методист',
      candidates: ['Соколов Сергей Сергеевич', 'Попов Павел Павлович'],
    },
    fullname: 'Иванов Иван Иванович',
    event: 'Принят на работу',
    resume: 'resume 3',
  },
  {
    vacancy: {
      name: 'Начальник отдела кадров',
      candidates: ['Лебедев Леонид Леонидович', 'Козлов Кирилл Кириллович'],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Резюме у заказчика',
    resume: 'resume 4',
  },
  {
    vacancy: {
      name: 'Менеджер по подбору персонала',
      candidates: ['Новиков Николай Николаевич', 'Морозов Михаил Михайлович'],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Проверка СБ',
    resume: 'resume 5',
  },
  {
    vacancy: {
      name: 'Дизайнер',
      candidates: ['Петров Петр Петрович', 'Смирнов Сергей Александрович'],
    },
    fullname: 'Иванов Иван Иванович',
    event: 'Принят на работу',
    resume: 'resume 1',
  },
  {
    vacancy: {
      name: 'Рекрутер',
      candidates: [
        'Васильев Василий Васильевич',
        'Кузнецов Константин Константинович',
      ],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Резюме у заказчика',
    resume: 'resume 2',
  },
  {
    vacancy: {
      name: 'Методист',
      candidates: ['Соколов Сергей Сергеевич', 'Попов Павел Павлович'],
    },
    fullname: 'Иванов Иван Иванович',
    event: 'Проверка СБ',
    resume: 'resume 3',
  },
  {
    vacancy: {
      name: 'Начальник отдела кадров',
      candidates: ['Лебедев Леонид Леонидович', 'Козлов Кирилл Кириллович'],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Проверка СБ',
    resume: 'resume 4',
  },
  {
    vacancy: {
      name: 'Менеджер по подбору персонала',
      candidates: ['Новиков Николай Николаевич', 'Морозов Михаил Михайлович'],
    },
    fullname: 'Киселёв Максим Олегович',
    event: 'Принят на работу',
    resume: 'resume 5',
  },
];

// вакансии
export let dataVacancy: IDataVacancy[] = [
  {
    date: '22.07.2020',
    vacancy: 'вакансия 1',
    status: 'В работе',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2012',
    vacancy: 'вакансия 2',
    status: 'Закрыта',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2021',
    vacancy: 'вакансия 1',
    status: 'Закрыта заказчиком',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2012',
    vacancy: 'вакансия 2',
    status: 'Новая заявка',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2023',
    vacancy: 'вакансия 1',
    status: 'Новая заявка',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2022',
    vacancy: 'вакансия 2',
    status: 'Отменена',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2017',
    vacancy: 'вакансия 1',
    status: 'Приостановлена',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2016',
    vacancy: 'вакансия 2',
    status: 'Сверх суммарной загрузки',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2021',
    vacancy: 'вакансия 1',
    status: 'Приостановлена',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2012',
    vacancy: 'вакансия 2',
    status: 'Приостановлена',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2021',
    vacancy: 'вакансия 1',
    status: 'Приостановлена',
    fullname: 'Иванов Иван Иванович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
  {
    date: '22.07.2012',
    vacancy: 'вакансия 2',
    status: 'Приостановлена',
    fullname: 'Иванов Иван Петрович',
    recruiterContacts: 'контакты рекрутера',
    resumeReviewed: 'Рассмотрено резюме 1',
    resumeSentToCustomer: 'Резюме направлено заказчику на рассмотрение 1',
    interviewWithTheCustomerWasConducted: 'Проведено интервью с заказчиком 1',
    checkSB: 'Проверка СБ 1',
    offer: 'Оффер 1',
    employed: 'Трудоустроены 1',
  },
];
